SexShop/SexShop/Controllers/EShopperController.cs
using Microsoft.AspNetCore.Mvc;
using SexShop.Data;
using SexShop.Models;
using SexShop.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Text.Json;

namespace SexShop.Controllers
{
    [Route("[controller]")]
    public class EShopperController : Controller
    {
        private readonly EShopperDbContext _db;
        public EShopperController (EShopperDbContext db)
        {
            _db = db;
        }
        [Route("/")]
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                ViewBag.count = 0;
            }
            else
            {
                ViewBag.count = cart.Count();
            }
            IEnumerable<ProductModel> objList = _db.Products;
            ViewBag.objList = objList;

            return View(objList);
        }

        [HttpGet]
        [Route("Category/{q}")]
        public IActionResult Category(string? q)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                ViewBag.count = 0;
            }
            else
            {
                ViewBag.count = cart.Count();
            }
            IEnumerable<ProductModel> categoryFromDb = 
                from obj in _db.Products
                where obj.Category == q
                select obj;

            IEnumerable<ProductModel> objList = _db.Products;
            ViewBag.objList = objList;

            return View(categoryFromDb);
        }
        [Route ("Detail/{id}")]
        public IActionResult Detail(int? id)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                ViewBag.count = 0;
            }
            else
            {
                ViewBag.count = cart.Count();
            }
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var product = _db.Products.FirstOrDefault(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            IEnumerable<ProductModel> objList = _db.Products;
            ViewBag.objList = objList;

            return View(product);
        }
        [Authorize]
        [Route ("Cart")]
        public IActionResult Cart()
        {
            var cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            try
            {
                ViewBag.total = cart.Sum(item => item.ProductModel.Price * item.Quantity);
            }
            catch(ArgumentNullException e)
            {
                ViewBag.total = "0";
            }
            if (cart == null)
            {
                ViewBag.count = 0;
            }
            else
            {
                ViewBag.count = cart.Count();
            }
            IEnumerable<ProductModel> objList = _db.Products;
            ViewBag.objList = objList;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route ("Cart")]
        public IActionResult Cart(CartModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.Cart.Add(obj);
                var resp = obj.CartJson.Remove(obj.CartJson.Length - 2, 1);
                var dict = JsonSerializer.Deserialize<Dictionary<string, string>>(resp);
                foreach (KeyValuePair<string, string> item in dict)
                {
                    ProductModel product = _db.Products.Find(int.Parse(item.Key));
                    product.Quantity -= int.Parse(item.Value);
                    _db.Products.Update(product);
                }
                _db.SaveChanges();
                return RedirectToAction("Redirect", new {id = obj.Id});
            }
            return View(obj);
        }
        private int isExist(int id)
        {
            List<ItemModel> cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].ProductModel.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        [Route("Buy/{id}")]
        public IActionResult Buy(int id)
        {
            if (SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart") == null)
            {
                List<ItemModel> cart = new();
                cart.Add(new ItemModel { ProductModel = _db.Products.Find(id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<ItemModel> cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new ItemModel { ProductModel = _db.Products.Find(id), Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Cart");
        }
        [Route("Decrease/{id}")]
        public IActionResult Decrease(int id)
        {
            List<ItemModel> cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            int index = isExist(id);
            if (cart[index].Quantity > 1)
            {
                cart[index].Quantity--;
            }
            else
            {
                return RedirectToAction("Remove", new { id = id });
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Cart");
        }
        [Route("Remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<ItemModel> cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            int index = isExist(id);
            try
            {
                cart.RemoveAt(index);
            }
            catch (ArgumentOutOfRangeException e)
            {

            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Cart");
        }

        public async Task<IActionResult> Query(string query)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                ViewBag.count = 0;
            }
            else
            {
                ViewBag.count = cart.Count();
            }
            var products = from p in _db.Products
                           select p;

            if (!String.IsNullOrEmpty(query))
            {
                products = products.Where(p => p.Name.ToLower().Contains(query.ToLower()));
            }
            IEnumerable<ProductModel> objList = _db.Products;
            ViewBag.objList = objList;

            return View(await products.ToListAsync());
        }
        [Route("Redirect/{id}")]
        public IActionResult Redirect(int? id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

SexShop/SexShop/Views/Admin/Create.cshtml
@model ProductModel

<form method="POST">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Adicionar produto</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Category"></label>
            <input asp-for="Category" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Barcode"></label>
            <input asp-for="Barcode" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary" style="width: 200px;">Criar</button>
        <a asp-action="Index" class="btn btn-primary" style="width: 200px;">
            Voltar
        </a>
    </div>
</form>

SexShop/SexShop/Views/Admin/Edit.cshtml
@model ProductModel

<form method="POST">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Adicionar produto</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Category"></label>
            <input asp-for="Category" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Barcode"></label>
            <input asp-for="Barcode" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary" style="width: 200px;">Salvar</button>
        <a asp-action="Index" class="btn btn-primary" style="width: 200px;">
            Voltar
        </a>
    </div>
</form>
<form class="btn-group" method="post" asp-route-id="@Model.Id">
    <button type="submit">Apagar</button>
</form>

SexShop/SexShop/Views/Admin/Index.cshtml
@model IEnumerable<ProductModel>
@{
    ViewData["Title"] = "Busca";
}


    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Categorias</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <partial name="_CategoriesPartial" />
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a asp-controller="EShopper" asp-action="Index" class="text-decoration-none d-block d-lg-none">
                        <img class="m-0 display-5" style="height: 75px;" src="~/img/logo.png" />
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav ml-auto py-0">
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->


    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">ADMIN</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a asp-action="Index">Luz Delas</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">ADMIN</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Shop Start -->
    <a asp-action="Create" class="btn btn-primary">Novo produto</a>
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <!-- Shop Product Start -->
            <div class="col-lg-9 col-md-12">
                <div class="row pb-3">
                    @foreach(var obj in Model)
                    {
                    <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <img class="img-fluid w-100" src="@obj.Image" alt="">
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3">@obj.Name</h6>
                                <div class="d-flex justify-content-center">
                                    <h6>R$ @obj.Price</h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                <a asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary p-0">Editar</a>
                                <form class="btn-group" method="post" asp-action="Delete" asp-route-id="@obj.Id">
                                    <button type="submit" class="btn btn-danger p-0">Apagar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->

SexShop/SexShop/Views/Admin/Order.cshtml
@Model CartModel
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Pedido @Model.Id de @Model.Username</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a asp-action="Index">Admin</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Pedido</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Cart Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Produtos</th>
                        <th>Preço</th>
                        <th>Quantidade</th>
                        <th>Total</th>
                        <th>Remover</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                @if(Model == null)
                {

                }
                else
                {
                    @foreach(KeyValuePair<string, string> item in ViewBag.order)
                    {
                            var product = ViewBag.products.Find(Int32.Parse(item.Key));
                        <tr>
                            <td class="align-middle"><img src="@product.Name" alt="" style="width: 50px;">@product.Name</td>
                            <td class="align-middle">R$ @product.Price</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <a asp-action="Decrease" asp-route-id="@product.Id">
                                            <button class="btn btn-sm btn-primary btn-minus" >
                                                    <i class="fa fa-minus"></i>
                                            </button>
                                        </a>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center" value="@Int32.Parse(item.Value)">
                                    <div class="input-group-btn">
                                        <a asp-action="Buy" asp-route-id="@product.Id">
                                            <button class="btn btn-sm btn-primary btn-plus">
                                                    <i class="fa fa-plus"></i>
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">R$ @(product.Price * Int32.Parse(item.Value))</td>
                            <td class="align-middle"><a asp-action="Remove" asp-route-id="@product.Id"><button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button></a></td>
                        </tr>
                    }
                }
            </tbody>
            </table>
        </div>
            <div class="col-lg-4">
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Resumo</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Subtotal</h6>
                            <h6 class="font-weight-medium">R$ @ViewBag.total</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Frete</h6>
                            <h6 class="font-weight-medium">R$ 0</h6>
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Total</h5>
                            <h5 class="font-weight-bold">R$ @ViewBag.total</h5>
                        </div>
                    </div>
                </div>
    </div>
</div>